 
version: '3'

services:
  database:
    container_name: laravel-database
    build:
      context: ./database
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    networks:
      - laravel-networks
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql

  laravel:
    container_name: laravel-api
    build: 
      context: ./php
    ports:
    - "8080:80"
    volumes:
    - ../app:/var/www
    networks:
      - laravel-networks
    environment:
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
    depends_on: 
      - database
networks:
  laravel-networks:
    driver: bridge